"""Generic DDL renderer used by the mock adapter and as a documented
emergency fallback when PowerDesigner's native GenerateDatabase is not
available.  Output is MySQL-flavoured, standard SQL.
"""

from __future__ import annotations

from typing import Any


def _type_sql(col: dict) -> str:
    dt = (col.get("data_type") or "VARCHAR").upper()
    length, precision = col.get("length"), col.get("precision")
    if length and precision:
        return f"{dt}({length},{precision})"
    if length and dt not in ("TEXT", "DATETIME", "DATE", "BOOLEAN", "BOOL"):
        return f"{dt}({length})"
    return dt


def render_ddl(adapter, model_id: str) -> str:
    info = adapter.get_model_info(model_id)
    tables = adapter.list_tables(model_id)
    refs = adapter.list_references(model_id)

    lines: list[str] = [
        f"-- DDL for model: {info.get('name')} ({info.get('kind')}, DBMS={info.get('dbms')})",
        "-- Generated by powerdesigner-mcp (fallback generator)",
    ]
    table_by_ref = {}
    create_lines, fk_lines, idx_lines = [], [], []
    for t in tables:
        full = adapter.get_table(model_id, t["ref"])
        table_by_ref[full["ref"]] = full
        cols_sql = []
        pk_cols = [c["code"] for c in full["columns"] if c.get("primary")]
        for c in full["columns"]:
            piece = f"  `{c['code']}` {_type_sql(c)}"
            if c.get("mandatory") or c.get("primary"):
                piece += " NOT NULL"
            if c.get("default_value") not in (None, ""):
                piece += f" DEFAULT {c['default_value']}"
            if c.get("comment"):
                piece += f" COMMENT '{c['comment'].replace(chr(39), chr(39)*2)}'"
            cols_sql.append(piece)
        if pk_cols:
            cols_sql.append(f"  PRIMARY KEY ({', '.join('`' + p + '`' for p in pk_cols)})")
        create_lines.append(f"CREATE TABLE `{full['code']}` (\n" + ",\n".join(cols_sql) + "\n);")
        for idx in full["indexes"]:
            cols = []
            for cref in idx["columns"]:
                col = next((c for c in full["columns"] if c["ref"] == cref), None)
                if col:
                    cols.append(col["code"])
            if not cols:
                continue
            kw = "UNIQUE INDEX" if idx.get("unique") else "INDEX"
            idx_lines.append(
                f"ALTER TABLE `{full['code']}` ADD {kw} `{idx['code']}` ({', '.join('`' + c + '`' for c in cols)});")

    for r in refs:
        parent = table_by_ref.get(r["parent_table"])
        child = table_by_ref.get(r["child_table"])
        if not parent or not child:
            continue
        pcodes = [c["code"] for c in parent["columns"] if c["ref"] in r["parent_columns"]]
        ccodes = [c["code"] for c in child["columns"] if c["ref"] in r["child_columns"]]
        if not pcodes or len(pcodes) != len(ccodes):
            continue
        fk_lines.append(
            f"ALTER TABLE `{child['code']}` ADD CONSTRAINT `{r['code']}` FOREIGN KEY "
            f"({', '.join('`' + c + '`' for c in ccodes)}) REFERENCES "
            f"`{parent['code']}` ({', '.join('`' + c + '`' for c in pcodes)});")

    lines += create_lines + idx_lines + fk_lines
    return "\n\n".join(lines) + "\n"
